// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaJfG7nWcdY2LEmpb6l_RfnnU3lOBRuWk',
    appId: '1:1006059968651:web:2d5e7be67abf254c38dc8e',
    messagingSenderId: '1006059968651',
    projectId: 'fitness-tracking-7d769',
    authDomain: 'fitness-tracking-7d769.firebaseapp.com',
    storageBucket: 'fitness-tracking-7d769.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc_vDLqxHHYYsZ1VplC7rDFNOH6Ug2-T8',
    appId: '1:1006059968651:android:7a1df174bde1f05838dc8e',
    messagingSenderId: '1006059968651',
    projectId: 'fitness-tracking-7d769',
    storageBucket: 'fitness-tracking-7d769.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJK4fXmlmYebGdT3vxMGozI4Vz4IffJaI',
    appId: '1:1006059968651:ios:b26f7caa7a74a1dd38dc8e',
    messagingSenderId: '1006059968651',
    projectId: 'fitness-tracking-7d769',
    storageBucket: 'fitness-tracking-7d769.appspot.com',
    iosBundleId: 'com.example.fitnessTracking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJK4fXmlmYebGdT3vxMGozI4Vz4IffJaI',
    appId: '1:1006059968651:ios:b26f7caa7a74a1dd38dc8e',
    messagingSenderId: '1006059968651',
    projectId: 'fitness-tracking-7d769',
    storageBucket: 'fitness-tracking-7d769.appspot.com',
    iosBundleId: 'com.example.fitnessTracking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaJfG7nWcdY2LEmpb6l_RfnnU3lOBRuWk',
    appId: '1:1006059968651:web:b8bfe6ebab1093b738dc8e',
    messagingSenderId: '1006059968651',
    projectId: 'fitness-tracking-7d769',
    authDomain: 'fitness-tracking-7d769.firebaseapp.com',
    storageBucket: 'fitness-tracking-7d769.appspot.com',
  );

}